//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos_GreenLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public int idDetalle { get; set; }
        public int idFactura { get; set; }
        public int idPlato { get; set; }
        public int cantidad { get; set; }
        public decimal precio { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Plato Plato { get; set; }
    }
}
