//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos_GreenLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public int idDetalle { get; set; }
        public int idFactura { get; set; }
        public int idPlato { get; set; }
        public int cantidad { get; set; }
        public decimal precio { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Plato Plato { get; set; }
    }
}
